### PR TITLE
fix: resolve incorrect endpoints for database bulk actions (#1626)

### LINKED ISSUE #1626: Bulk Actions Use Incorrect Endpoints for Database Services (PostgreSQL, Redis)
### To Reproduce

1. Create a project with:
- A Docker Compose service (e.g., Gitea)
- A Redis database
- A PostgreSQL database

2. Select all services in the Dokploy UI and use bulk actions to "Start" or "Stop" them.
3. Observe API calls in the browser's developer tools or logs:
- **Bulk Start:**

```javascript
// Gitea (works)
fetch("http://localhost:3000/api/trpc/compose.start?batch=1", {
  "body": "{\"0\":{\"json\":{\"composeId\":\"kAyQkZ_D0RgZDpoB94Ypv\"}}}",
  "method": "POST"
});

// Redis (fails)
fetch("http://localhost:3000/api/trpc/compose.start?batch=1", {
  "body": "{\"0\":{\"json\":{\"composeId\":\"c-f7WV5owm8fK9RFdQkJU\"}}}",
  "method": "POST"
});

// PostgreSQL (fails)
fetch("http://localhost:3000/api/trpc/compose.start?batch=1", {
  "body": "{\"0\":{\"json\":{\"composeId\":\"VU8-07UO2t4mfAp27zxg3\"}}}",
  "method": "POST"
});
```

- **Bulk Stop:**

```javascript
// Gitea (works)
fetch("http://localhost:3000/api/trpc/compose.stop?batch=1", {
  "body": "{\"0\":{\"json\":{\"composeId\":\"kAyQkZ_D0RgZDpoB94Ypv\"}}}",
  "method": "POST"
});

// Redis (fails)
fetch("http://localhost:3000/api/trpc/compose.stop?batch=1", {
  "body": "{\"0\":{\"json\":{\"composeId\":\"c-f7WV5owm8fK9RFdQkJU\"}}}",
  "method": "POST"
});

// PostgreSQL (fails)
fetch("http://localhost:3000/api/trpc/compose.stop?batch=1", {
  "body": "{\"0\":{\"json\":{\"composeId\":\"VU8-07UO2t4mfAp27zxg3\"}}}",
  "method": "POST"
});
```

4. Database services fail with an error (e.g., "Error stopping service"), while Gitea starts/stops successfully.

### Current vs. Expected behavior

Bulk actions should use the correct endpoints based on service type:
- For Redis: /api/trpc/redis.start and /api/trpc/redis.stop.
- For PostgreSQL: /api/trpc/postgres.start and /api/trpc/postgres.stop.
- For Docker Compose: /api/trpc/compose.start and /api/trpc/compose.stop.

**Correct API calls for databases:**

```javascript
// Start Redis
fetch("http://localhost:3000/api/trpc/redis.start?batch=1", {
  "body": "{\"0\":{\"json\":{\"redisId\":\"c-f7WV5owm8fK9RFdQkJU\"}}}",
  "method": "POST"
});

// Stop Redis
fetch("http://localhost:3000/api/trpc/redis.stop?batch=1", {
  "body": "{\"0\":{\"json\":{\"redisId\":\"c-f7WV5owm8fK9RFdQkJU\"}}}",
  "method": "POST"
});

// Start PostgreSQL
fetch("http://localhost:3000/api/trpc/postgres.start?batch=1", {
  "body": "{\"0\":{\"json\":{\"postgresId\":\"VU8-07UO2t4mfAp27zxg3\"}}}",
  "method": "POST"
});

// Stop PostgreSQL
fetch("http://localhost:3000/api/trpc/postgres.stop?batch=1", {
  "body": "{\"0\":{\"json\":{\"postgresId\":\"VU8-07UO2t4mfAp27zxg3\"}}}",
  "method": "POST"
});
```

**Actual Behavior**
Bulk actions incorrectly apply /api/trpc/compose.start and /api/trpc/compose.stop to all services, causing database operations to fail.

### Provide environment information

```bash
OS: Ubuntu 24.04
Dokploy: 0.21.3
Databases: Postgres:16, Redis:7
```

### Which area(s) are affected? (Select all that apply)

Databases

### Are you deploying the applications where Dokploy is installed or on a remote server?

Both

### Additional context

_No response_

### Will you send a PR to fix it?

Maybe, need help

### PR DESCRIPTION
**Pull request by krokodaws**
Update bulk action endpoints for database services:
- Use `/api/trpc/redis.start` and `/api/trpc/redis.stop` for Redis
- Use `/api/trpc/postgres.start` and `/api/trpc/postgres.stop` for PostgreSQL
- Retain `/api/trpc/compose.start` and `/api/trpc/compose.stop` for Docker Compose services

Tested with a project including Gitea, Redis, and PostgreSQL. Bulk start/stop operations now function correctly for all service types.

Closes #1626

### CODE REVIEW

**Comment by gnpaone** [comment]
Hey @krokodaws check this too https://github.com/krokodaws/dokploy/pull/1 I have refactored code to make it simpler

File: apps/dokploy/pages/dashboard/project/[projectId].tsx [hunk 1]
```diff
@@ -306,217 +304,96 @@ const Project = (
...
-			toast.success(`${success} services deleted successfully`);
+			toast.success(`${success} services ${action}ed successfully`);
 			refetch();
 		}
+		setIsBulkActionLoading(false);
 		setSelectedServices([]);
 		setIsDropdownOpen(false);
-		setIsBulkActionLoading(false);
+		if (action === "move") setIsMoveDialogOpen(false);
 	};
```
Comment (Siumauricio) [inline apps/dokploy/pages/dashboard/project/[projectId].tsx]: I'd rather have the way we had it, I feel it's easier to add and modify, than a method that is somewhat complex

Could you simply add the missing mutations to each object in the service?

**Review by Siumauricio — CHANGES_REQUESTED** [review]

File: apps/dokploy/pages/dashboard/project/[projectId].tsx (hunk 1 above)
Comment (krokodaws) [reply apps/dokploy/pages/dashboard/project/[projectId].tsx]: OK, I've returned all the changes to their original form.

**Review by Siumauricio — APPROVED** [review]
