### PR TITLE
fix(traefik-setup): now pulling the traefik image to make it sure it's present locally

### LINKED ISSUE #2029: pnpm run dokploy:setup command not pulling traefik version if it's not present locally
### To Reproduce

1. If you have the traefik version locally, remove it from docker images
2. Open a terminal and execute the following commands.
3. git clone https://github.com/dokploy/dokploy.git
4. cd dokploy
5. pnpm install
6. cp apps/dokploy/.env.example apps/dokploy/.env
7. pnpm run dokploy:setup # this will trigger the error

### Current vs. Expected behavior

**Current behavior**:
```
pnpm run dokploy:setup

> dokploy@ dokploy:setup /Users/killianvincent/Documents/dokploy2/dokploy
> pnpm --filter=dokploy run setup


> dokploy@v0.22.7 setup /Users/killianvincent/Documents/dokploy2/dokploy/apps/dokploy
> tsx -r dotenv/config setup.ts && sleep 5 && pnpm run migration:run

Default middlewares already exists
Swarm is already initilized
Network is already initilized
Main config already exists
Default traefik config already exists
No existing service to remove
No existing container to remove
Failed to initialize Traefik: Error: (HTTP code 404) no such container - No such image: traefik:v3.1.2 
    at /Users/killianvincent/Documents/dokploy2/dokploy/node_modules/.pnpm/docker-modem@5.0.6/node_modules/docker-modem/lib/modem.js:383:17
    at getCause (/Users/killianvincent/Documents/dokploy2/dokploy/node_modules/.pnpm/docker-modem@5.0.6/node_modules/docker-modem/lib/modem.js:418:7)
    at Modem.buildPayload (/Users/killianvincent/Documents/dokploy2/dokploy/node_modules/.pnpm/docker-modem@5.0.6/node_modules/docker-modem/lib/modem.js:379:5)
    at IncomingMessage.<anonymous> (/Users/killianvincent/Documents/dokploy2/dokploy/node_modules/.pnpm/docker-modem@5.0.6/node_modules/docker-modem/lib/modem.js:347:16)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  reason: 'no such container',
  statusCode: 404,
  json: { message: 'No such image: traefik:v3.1.2' }
}
Error in dokploy setup Error: (HTTP code 404) no such container - No such image: traefik:v3.1.2 
    at /Users/killianvincent/Documents/dokploy2/dokploy/node_modules/.pnpm/docker-modem@5.0.6/node_modules/docker-modem/lib/modem.js:383:17
    at getCause (/Users/killianvincent/Documents/dokploy2/dokploy/node_modules/.pnpm/docker-modem@5.0.6/node_modules/docker-modem/lib/modem.js:418:7)
    at Modem.buildPayload (/Users/killianvincent/Documents/dokploy2/dokploy/node_modules/.pnpm/docker-modem@5.0.6/node_modules/docker-modem/lib/modem.js:379:5)
    at IncomingMessage.<anonymous> (/Users/killianvincent/Documents/dokploy2/dokploy/node_modules/.pnpm/docker-modem@5.0.6/node_modules/docker-modem/lib/modem.js:347:16)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  reason: 'no such container',
  statusCode: 404,
  json: { message: 'No such image: traefik:v3.1.2' }
}

> dokploy@v0.22.7 migration:run /Users/killianvincent/Documents/dokploy2/dokploy/apps/dokploy
> tsx -r dotenv/config migration.ts

Migration failed AggregateError [ECONNREFUSED]: 
    at internalConnectMultiple (node:net:1118:18)
    at afterConnectMultiple (node:net:1685:7) {
  code: 'ECONNREFUSED',
  [errors]: [
    Error: connect ECONNREFUSED 127.0.0.1:5432
        at createConnectionError (node:net:1648:14)
        at afterConnectMultiple (node:net:1678:16) {
      errno: -61,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 5432
    },
    Error: connect ECONNREFUSED ::1:5432
        at createConnectionError (node:net:1648:14)
        at afterConnectMultiple (node:net:1678:16) {
      errno: -61,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '::1',
      port: 5432
    }
  ]
}
```

**Expected behavior:**
It should pull the image automatically

### Provide environment information

```bash
OS: MacOS 15.5 (24F74)
Git Branch: canary
```

### Which area(s) are affected? (Select all that apply)

Installation

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Additional context

_No response_

### Will you send a PR to fix it?

Yes

### PR DESCRIPTION
**Pull request by s1nyx**
Hi,

- Fixes #2029 
- Added the pulling of the traefik image name/version during the setup (`pnpm run dokploy:setup`) when it's not present locally otherwise it throws an error if you don't have it.
- I didn't add any tests because it seems like there isn't any on the setup part ?

### CODE REVIEW

File: packages/server/src/setup/traefik-setup.ts [hunk 1]
```diff
@@ -124,6 +124,26 @@ export const initializeTraefik = async ({
...
+			if (error?.statusCode === 404) {
+				console.log(`Image ${imageName} not found, pulling...`);
+				const stream = await docker.pull(imageName);
+				await new Promise((resolve, reject) => {
+					// eslint-disable-next-line @typescript-eslint/ban-ts-comment
+					// @ts-ignore
+					docker.modem.followProgress(stream, (err: Error, res: any) =>
+						err ? reject(err) : resolve(res),
+					);
+				});
```
Comment (Marukome0743) [inline packages/server/src/setup/traefik-setup.ts]:
```suggestion
				await new Promise((resolve, reject) => {
					docker.modem.followProgress(stream, (err: Error | null, res: any) =>
						err ? reject(err) : resolve(res),
					);
				});
```

This code pathed the eslint check.
Can you build with it without any errors?
